name: "MPCnC Babo V1"
board: "Protoneer CNC Shield V3.00"

kinematics:
  cartesian:

stepping:
  engine: RMT
  idle_ms: 250
  dir_delay_us: 1
  pulse_us: 2
  disable_delay_us: 0

axes:
  shared_stepper_disable_pin: gpio.16:high
  
  x:
    steps_per_mm: 50
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 765
    soft_limits: true
    homing:
      allow_single_axis: true
      cycle: 2
      mpos_mm: 0
      seek_mm_per_min: 500
      positive_direction: false
    motor0:
      pulloff_mm: 3
      limit_neg_pin: gpio.4:low:pu
      hard_limits: true
      stepstick:
        direction_pin: gpio.18
        step_pin: gpio.22

  y:
    steps_per_mm: 50
    max_rate_mm_per_min: 6000
    acceleration_mm_per_sec2: 200
    max_travel_mm: 570
    soft_limits: true
    homing:
      allow_single_axis: true
      cycle: 2
      mpos_mm: 0
      seek_mm_per_min: 500
      positive_direction: false
    motor0:
      pulloff_mm: 3
      limit_neg_pin: gpio.12:low:pu
      hard_limits: true
      stepstick:
        direction_pin: gpio.5
        step_pin: gpio.21

  z:
    steps_per_mm: 100
    max_rate_mm_per_min: 100
    acceleration_mm_per_sec2: 10
    max_travel_mm: 135
    soft_limits: true
    motor0:
      stepstick:
        direction_pin: gpio.17
        step_pin: gpio.19

probe:
  pin: gpio.13:low:pu
